### ISSUE TITLE
Broken link to the PanoContext-fR dataset

### ISSUE THREAD

**Issue by rpautrat** [ElderLab-York-University/OnlinefR#1]
Hi, thank you for the great work and for releasing the code and dataset.

It seems that the link to the PanoContext-fR dataset is broken though, as the access is only allowed for people from the York University... Would it be possible to provide a link accessible to everyone? Thank you!

**Comment by yimingqian** [comment]
it is now fixed

**Comment by rpautrat** [comment]
Thank you!
