### ISSUE TITLE
Unrecognized function or variable 'round2frac2'.

### ISSUE THREAD

**Issue by pythonzz0622** [ElderLab-York-University/OnlinefR#3]
Hello, I encountered the error 'Unrecognized function or variable 'round2frac2'' while using MATLAB.

I’m not familiar with the program, so I’m unsure how to fix this issue. Could you please help me understand how to resolve it? I would really appreciate your assistance.

**Comment by yimingqian** [comment]
The Matlab file round2frac2.m is in the following folder 
MCMLSD/code/ElderZuckerEdgeDetector/
